### ISSUE TITLE
pls consider throwing obvious error when limit is a non-positive integer

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1331] opened 2016-11-29 03:51 UTC
On latest version of async

I tried (for the heck of it), a limit of 0

```js
const async = require('async');

async.eachLimit([ 1, 2, 3 ], 0, function (item, cb) {
  console.log('item => ', item);
  process.nextTick(cb)
}, function (err) {
  console.log('error => ',err);
});

```

just curious what the rationale is for not throwing an error or not passing an error back in the final callback (that may be new Error('Concurrency of 0 is not valid') or whatever?

**Comment by aearly** [comment] 2016-11-29 05:33
👍 for this, but it would be a breaking change.

**Comment by ORESoftware** [comment] 2016-11-29 07:10
It's actually a feature because you can skip to the final callback, I just think that there should be an error there. If the user wants to ignore the error, they can do that.
Definitely understand that it would be a breaking change.

**Comment by megawac** [comment] 2016-11-29 15:30
Closing as dupe of #1249

**Closed by megawac** 2016-11-29 15:30 UTC
Labels: breaking-change, enhancement

**Comment by megawac** [comment] 2016-11-29 15:31
I would be fine with doing this in a minor release and considering it a bug fix. Thoughts @aearly?

**Comment by aearly** [comment] 2016-11-29 18:23
I'd consider it a breaking change.  Some people might be using or inadvertently relying on that strange behavior.
