### ISSUE TITLE
no error is thrown when the dependencies are wrong in async.auto

### ISSUE THREAD

**Issue by zhaoyao91** [caolan/async#736] opened 2015-03-18 05:48 UTC
I am coding a component loader with asycn.auto.
but there is no any error thrown when the dependencies are wrong, such as that
comp1 need comp2 and comp2 need comp1
or comp1 need comp3, but there is no comp3

how can i do with this? thanks

**Comment by aearly** [comment] 2015-03-18 07:46
#663 is related.  Still waiting for @caolan to merge and release....

**Comment by aearly** [comment] 2015-05-19 19:23
Duplicate of #663

**Closed by aearly** 2015-05-19 19:23 UTC
Labels: bug
