### ISSUE TITLE
Async does not protect against array modifications during the function's runtime

### ISSUE THREAD

**Issue by bradens** [caolan/async#572] opened 2014-07-04 00:14 UTC
When you have an asynchronous call eg. `async.each`, and during that runtime, the array which is passed in has modifications to it, then it may never finish, or will call the callback twice. 

Example:
```coffeescript
async = require "async" 
arr = [1, 2, 3]  
async.each arr, ((i, cb) -> console.log "i"; setImmediate(cb)), (err) -> console.log "done" 
arr.push(4)
```

This example loops through the 3 original array elements, and prints `i` but then never calls the callback, because in `async.each` it's doing: 

```javascript 
if (completed >= arr.length) {
  callback(null);
}
```

When looking at the async code, it's doing a comparison against `arr.length` which can change...would it not be better to store the original array length and do a comparison against that, ensuring that the completed callback will be called?

Fiddle: 
http://jsfiddle.net/4ysKX/1/

**Comment by aearly** [comment] 2015-06-01 03:59
This is a duplicate of #557.

**Closed by aearly** 2015-06-01 03:59 UTC
Labels: bug

**Comment by ORESoftware** [comment] 2017-06-25 06:10
Did async end up disallowing array modifications after the fact? I have a use case where it would be nice to modify the original array after the fact, so as to iterate on more elements than initially.
