### ISSUE TITLE
map with Object

### ISSUE THREAD

**Issue by allevo** [caolan/async#689] opened 2014-12-28 23:03 UTC
I'm very happy if async can accept an Object as first parameter of map. The behaviour is like parallel, the result is an object with the same keys of the input.

Are you interested in?

**Comment by aearly** [comment] 2015-01-07 19:48
As a workaround, you can convert your object to an array of `[key, value]` tuples and then zip the result back up.  Easy with `_.pairs` and `_.zipObject`, if you're using Lodash.

```
async.map(_.pairs(obj), function (tuple, cb) {
  var key = tuple[0];
  var value = tuple[1];
  // do something with key and value
  //..
  cb(null, [key, newValue]);
}, function (err, result) {
  if (err) return callback(err);
  callback(null, _.zipObject(result));
})
```

**Comment by aearly** [comment] 2015-05-19 19:17
Dupe of #321

**Closed by aearly** 2015-05-19 19:17 UTC
Labels: feature
