### ISSUE TITLE
mapLimit without callback only executes "limit" amount of times

### ISSUE THREAD

**Issue by bertyhell** [caolan/async#1685] opened 2019-09-11 11:16 UTC
**What version of async are you using?**
3.1.0

**Which environment did the issue occur in (Node version/browser version)**
node: 10.16.0

**What did you do? Please include a minimal reproducible case illustrating issue.**
```Javascript
"use strict";
const delay = (timeout) => {
    return new Promise((resolve) => {
        setTimeout(resolve, timeout);
    });
};
const myAsyncFunction = async function () {
    return async.mapLimit([1, 2, 3, 4, 5], 3, async (num) => {
        await delay(2000);
        console.log(num * 2);
        return num * 2;
    });
};
myAsyncFunction().then((result) => {
    console.log(result);
});
```
https://codepen.io/bertyhell/pen/NWKMRvY?editors=0012

**What did you expect to happen?**
The code should output: 2, 4, 6, 8, 10
Then at the end of the mapLimit the code should log the array:  [2, 4, 6, 8, 10]

**What was the actual result?**
The code outputs: 2, 4, 6
The final then is never called, the await on the async.mapLimit just hangs

**Comment by luddd3** [comment] 2019-09-23 15:49
I can confirm that the code works as intended in 3.1.0 with node 12.9.0.

**Comment by aearly** [comment] 2019-09-23 23:26
Are you using Babel or any other transpiler perchance?

**Comment by luddd3** [comment] 2019-09-24 04:21
The linked codepen worked when I switched preprocessor from "Typescript" to "None"

**Comment by bertyhell** [comment] 2019-09-24 11:04
So it is an incompatibility between async and the typescript compiler?
Because i first noticed this issue in a project that uses typescript

**Comment by aearly** [comment] 2019-09-24 18:31
If typescript is compiling `async` functions down to generator function, then Async can't tell if it's an `async` function or a callback-accepting function.  Can you tell TS to target ES2017 rather than ES2015?

The other (ugly) solution is to wrap `async` functions with `asyncify`: 

```js
    return async.mapLimit([1, 2, 3, 4, 5], 3, asyncify(async (num) => {
        await delay(2000);
        console.log(num * 2);
        return num * 2;
    }));
```

**Comment by bertyhell** [comment] 2019-09-25 09:30
Yes, then it works:
tsconfig.json:
```JSON
{
  "compilerOptions": {
    "target": "es2017"
  }
}
```

I thought you detected an async function because no callback method is passed. 

Or would that cause breaking changes for people that didn't pass a callback, but still expected the callback version of the async lib function to be used?

**Comment by aearly** [comment] 2019-09-25 22:00
> This means async v3 isn't compatible with typescript for targets < es2017 😭

This is correct, if you want `async` functions to be handled automatically.

**Comment by aearly** [comment] 2019-09-25 22:02
In theory, `tsc`/`babel` could add the `fn[Symbol.toStringTag] = 'AsyncFunction'` to transpiled `async` functions and things would work.

**Comment by aearly** [comment] 2020-02-16 01:11
Closing, as this is a documented issue with transpiled `async` functions.

**Closed by aearly** 2020-02-16 01:11 UTC
