### ISSUE TITLE
async.forEachOf

### ISSUE THREAD

**Issue by the1mills** [caolan/async#925] opened 2015-10-07 18:55 UTC
async.forEachOf(dbs, function (client, key, cb) {})

async.forEachOf is not a function, can you remove from your docs? or correct me?

**Comment by ex1st** [comment] 2015-10-07 19:38
@the1mills https://github.com/caolan/async/blob/master/lib/async.js#L229

**Comment by paglias** [comment] 2015-10-08 17:25
Just found this

**Comment by paglias** [comment] 2015-10-08 17:26
sorry my fault, I was using a version prior to 1 

@the1mills make sure you're using at least version 1

**Comment by the1mills** [comment] 2015-10-08 18:25
yeah thanks

**Comment by megawac** [comment] 2015-10-14 14:05
Yep, duplicate of https://github.com/caolan/async/issues/878

**Closed by megawac** 2015-10-14 14:05 UTC
