### ISSUE TITLE
leverage lodash

### ISSUE THREAD

**Issue by jdalton** [caolan/async#914] opened 2015-09-21 17:42 UTC
I know @megawac is experimenting with lodash-es modules to reduce some of the lower level cruft so async can focus on other bits. I'm opening the issue here to give it a bigger spotlight and to encourage discussion/contribution to his experiments. Btw I'm totally open to helping in this area from the lodash side of things.

**Comment by aearly** [comment] 2015-09-21 19:05
I"m totally :+1: on this, but we haven't figured out the best way to package multiple modules for the  standalone browser build.  (In addition to having npm deps, we also want to split up the singular  async.js into one file per method.)  The straightforward solution is to use browserify, but it adds a lot or overhead.

I wonder how @megawac 's experiments are going....

**Comment by jdalton** [comment] 2015-09-21 19:12
For the experiments I retooled the [lodash-es](https://github.com/lodash/lodash/blob/7d1253135488bef0dcc4bab200257b815052858f/lodash.js#L552-L786) build to export modules so that
```js
import chunk from 'lodash-es'
```

was doable to allow cherry-picking (just the `chunk` method).

**Comment by jdalton** [comment] 2015-09-21 19:13
I know he's kicking around [rollup](https://github.com/rollup/rollup).

**Comment by megawac** [comment] 2015-09-21 19:17
So the basic idea is to default in using a modular build (i.e. a bunch of `lib/<function>.js` ala ramda but with third party module support) which all use CJS/ES6 imports for required async and lodash methods. A monolithic build (with a clever preprocessing step) would also be created using [rollup](https://www.npmjs.com/package/rollup).

Rollup doesn't seem quite ready yet, and runs into a couple issues with lodash-es at the moment -- I've been punting on doing a debug session to figure out whats up on that front.

**Comment by aearly** [comment] 2015-09-21 19:20
ES6 seems like it will enable a lot of bundling optimizations -- e.g. when multiple modules depend on the same thing it can probably be pulled into a single var in a parent scope, in addition to cherry-picking single exports.

A shame you can't do it confidently today with browserify, since with `var _ = require("lodash")`, `_` could be rebound later in the module, but in theory `const _ = require("lodash")` is something that could be pulled into the top-level scope for a bundle.  With ES6 modules that export bindings, it seems that you'd always want to pull those `export default` bindings to the top level scope since they wouldn't change.

**Comment by jdalton** [comment] 2015-09-21 19:23
Pulling in @Rich-Harris for the rollup issue.

@aearly 
On a side note @megawac has [babel plugin](https://github.com/megawac/babel-plugin-lodash#example) to handle some of the syntax wins without es6.

**Comment by aearly** [comment] 2015-09-21 20:53
Yeah, that works really nicely for lodash, but it would be great to have something that works across the board for any lib that follows a couple conventions.

**Comment by Rich-Harris** [comment] 2015-09-21 21:04
@megawac lmk if there's anything I can do to help figure out the problem(s) – am always grateful for test cases

**Comment by aearly** [comment] 2015-10-22 06:41
I finally took a look at rollup, it seems really interesting!  It  looks like we could easily use it to build the core async lib from small ES6 modules, then perhaps use browserify or webpack to bundle in npm dependencies for the browser.

It looks like rollup isn't handling on `export { default as slice } from './array/slice';` style declarations.  I played around with rollup's in-browser playground, and it seemed to choke on that.

**Comment by megawac** [comment] 2015-10-22 12:28
The biggest issue stalling adoption is to go over open pull requests and
accept or reject. After that we can start modularization + rollup

**Comment by Rich-Harris** [comment] 2015-10-22 15:16
@aearly interesting – any chance you could reproduce the bug so we can take a look? [This seems to work](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22amd%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20%7B%20slice%20%7D%20from%20'.%2Farray.js'%3B%5Cnvar%20arr%20%3D%20%5B%201%2C%202%2C%203%20%5D%3B%5Cnconsole.log(%20slice(%20arr%20)%20)%3B%22%7D%2C%7B%22name%22%3A%22slice.js%22%2C%22code%22%3A%22export%20default%20function%20slice%20(%20array%20)%20%7B%5Cn%20return%20array.slice()%3B%5Cn%7D%22%7D%2C%7B%22name%22%3A%22array.js%22%2C%22code%22%3A%22export%20%7B%20default%20as%20slice%20%7D%20from%20'.%2Fslice.js'%3B%22%7D%5D%7D) but I'm probably missing something. Thanks!

**Comment by aearly** [comment] 2015-10-26 00:41
@Rich-Harris  I lost the tab where I was playing around with modules, and I can't seem to reproduce it.  I probably was doing something that was actually an error.   lodash-es6 is worth another shot.

@megawac I've gone through the majority of open pull requests.  I think I might do a 1.5.0 release, then we can focus on some of these larger changes.

**Comment by megawac** [comment] 2015-10-26 00:47
Good stuff @aearly!

**Comment by jdalton** [comment] 2015-10-26 01:42
I updated the es build to [separate the default exports into their own modules](https://github.com/lodash/lodash/blob/es/lodash.js).

**Comment by aearly** [comment] 2016-02-16 23:34
Closing this since we've done it in #996!

**Closed by aearly** 2016-02-16 23:34 UTC
Labels: feature
